version: '3.3'
services:
  prueba-backend:
    image: 'prueba-backend'
    build:
        dockerfile: ./Dockerfile
        context: .
    ports:
      - '8080:8080'
    depends_on:
      - mongodb_container
    networks:
      prueba-backend:

  mongodb_container:
    image: mongo:latest
    expose:
      - 27017
    networks:
      prueba-backend:

networks:
  prueba-backend:
    driver: bridge